[project]
name = "neurovolume"
version = "0.1.0a1"
description = "Python library for Neurovolume. Build VDBs for scientific visualizations"
readme = "README.md"
authors = [
    { name = "joachimbbp", email = "jbbpfefferkorn@gmail.com" }
]
# developed using 3.14 but blender uses 3.11.13,
requires-python = ">=3.11.13" 
dependencies = [
    "numpy>=2.3.5",
    "pytest>=9.0.1",
    "ziglang>=0.15.1",
]

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"


